apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logger-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: azurefile
  accessModes:
  - ReadWriteMany
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logger-deploy
  name: logger-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: logger-deploy
    spec:
      containers:
      - image: #LOGGERIMAGE#
        name: logger
        args: ["10000","15000"]
        env:
          - name: LOG_DIR
            value: /logs
        volumeMounts:
          - mountPath: "/logs"
            name: volume
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - image: busybox:latest
        name: logger-sidecar
        command: ["/bin/sh"]
        args: ["-c","sleep 60;tail -fn+1 /logs/system.$HOSTNAME.log; exit 0;"]
        volumeMounts:
          - mountPath: "/logs"
            name: volume
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: logger-pvc
